parser: babel-eslint

extends:
  - airbnb
  - plugin:flowtype/recommended

plugins:
  - react
  - babel
  - jsx-a11y
  - import
  - flowtype
env:
  browser: true
  node: true
  es6: true

rules:

  max-len: [error, 100]
  semi: [error, never]
  comma-dangle: [error, always-multiline]
  quotes: [error, single]
  arrow-parens: [error, as-needed]
  padded-blocks: off
  react/jsx-tag-spacing: [error, {closingSlash: never, beforeSelfClosing: never, afterOpening: never}]
  no-unused-vars: [error, {args: after-used, argsIgnorePattern: '^_'}]
  no-trailing-spaces: [error, { skipBlankLines: true }]
  react/sort-comp: off #[error, [order: 'static-methods', 'lifecycle', 'everything-else', 'render']]
  react/prefer-stateless-function: warn
  react/jsx-filename-extension: off
  react/require-default-props: off
  jsx-a11y/href-no-hash: off #todo: href-no-hash was removed but still required by airbnv
  babel/object-curly-spacing: [error, never]
  object-curly-spacing: off
  react/jsx-curly-spacing: [error, never]
  class-methods-use-this: error
  react/prop-types: off
  no-nested-ternary: off
  no-mixed-operators: [error, {allowSamePrecedence: true}]
  no-underscore-dangle: off

  linebreak-style: off
  no-console: off
  no-alert: off

settings:
  import/resolver:
    webpack:
      config:
        resolve:
          modules: [ node_modules, src ]
          #extensions: [.js, .jsx, .ts]
